[application]
name = "qrtransfer"
default_platform = "web"

[web.app]
title = "qrtransfer"

[web.resource]
style = ["https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css"]
script = [
    "https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.bundle.min.js",
]

[web.resource.dev]
