[application]
name = "qrtransfer"
default_platform = "web"

[web.app]
title = "qrtransfer"

[web.resource]
style = ["assets/bootstrap/bootstrap.min.css"]
script = ["assets/bootstrap/bootstrap.bundle.min.js"]

[web.resource.dev]
